### ISSUE TITLE
Transforms is not included in the packages list in setup.py

### ISSUE THREAD

**Issue by stewy33** [joseppinilla/embera#7]
The packages list in setup.py:

```python
packages = ['embera',
            'embera.architectures',
            'embera.benchmark',
            'embera.composites',
            'embera.interfaces',
            'embera.preprocess',
            'embera.utilities',
            ]
```
needs to include `embera.transform` to install correctly.
Could also use `packages = setuptools.find_packages()` if you prefer.

Super quick fix, I can handle it if you'd like :)

**Comment by joseppinilla** [comment]
Awesome!
Yeah, transforms is still very much work in progress (as is most of this repo), but thanks a lot for your interest.
If you submit a PR I'll make sure to check it and merge.

**Comment by joseppinilla** [comment]
Added in ca2096d3ced5f6ca36807db0c8717c0853c53925
